-- Generated by Ora2Pg, the Oracle database Schema converter, version 23.2
-- Copyright 2000-2022 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:host=NRKDB01.BCGOV;SERVICE_NAME=ENVPROD1.NRS.BCGOV;port=1521

SET client_encoding TO 'UTF8';

SET search_path = cwi_txn,public;

CREATE TABLE spi_agencies (
	agency_id bigint ,
	agency_cd varchar(25) ,
	agency_name varchar(150),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE spi_agencies IS 'Agencies that fund or support wildlife inventory projects.';
COMMENT ON COLUMN spi_agencies.agency_cd IS 'Abbreviation for Agency (FRBC, CRII, CLIB, HCTF)';
COMMENT ON COLUMN spi_agencies.agency_id IS 'System generated identifier for Agency.';
COMMENT ON COLUMN spi_agencies.agency_name IS 'The name of the funding or supporting agency for the project.';
COMMENT ON COLUMN spi_agencies.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN spi_agencies.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN spi_agencies.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN spi_agencies.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
ALTER TABLE spi_agencies ADD PRIMARY KEY (agency_id);
ALTER TABLE spi_agencies ADD UNIQUE (agency_cd);

CREATE TABLE spi_codes (
	type varchar(50) ,
	code varchar(25) ,
	value varchar(200) ,
	display_sequence integer,
	description varchar(512),
	end_date timestamp,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE spi_codes IS 'Codes, values, descriptions and (code) types used for lookup values in SPI.';
COMMENT ON COLUMN spi_codes.code IS 'The unique code (within a type) used to identify a SPI code.';
COMMENT ON COLUMN spi_codes.description IS 'The description of the unique cod';
COMMENT ON COLUMN spi_codes.display_sequence IS 'The display order for any one type of cod';
COMMENT ON COLUMN spi_codes.end_date IS 'The data when the code expires.';
COMMENT ON COLUMN spi_codes.type IS 'Code for identifying a group of SPI codes.';
COMMENT ON COLUMN spi_codes.value IS 'The full name that describes the cod';
COMMENT ON COLUMN spi_codes.when_created IS 'When was this record created.';
COMMENT ON COLUMN spi_codes.when_updated IS 'When was this record updated.';
COMMENT ON COLUMN spi_codes.who_created IS 'Who created this record.';
COMMENT ON COLUMN spi_codes.who_updated IS 'Who last updated this record.';
ALTER TABLE spi_codes ADD PRIMARY KEY (type,code);

CREATE TABLE spi_data_types (
	data_type_id bigint ,
	prompt varchar(65) ,
	data_type varchar(15) ,
	data_type_comment varchar(512),
	help_text varchar(1500) ,
	description varchar(1500),
	validation_property varchar(512),
	on_error varchar(250),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE spi_data_types IS 'One type of datum or observation column which can be collectedas part of a wildlife observation.';
COMMENT ON COLUMN spi_data_types.data_type IS 'The type of data (character, number) of the observation column.';
COMMENT ON COLUMN spi_data_types.data_type_comment IS 'Any additional comments on the data value.';
COMMENT ON COLUMN spi_data_types.data_type_id IS 'System generated identifier for a Data-Type.';
COMMENT ON COLUMN spi_data_types.description IS 'Description of the column.';
COMMENT ON COLUMN spi_data_types.help_text IS 'Text from the Species Survey Forms documentation.';
COMMENT ON COLUMN spi_data_types.on_error IS 'The lookup code to display when the validation fails.';
COMMENT ON COLUMN spi_data_types.prompt IS 'Label for the corresponding Wildlife-Observation column';
COMMENT ON COLUMN spi_data_types.validation_property IS 'Obsolete column - unused in this version of SPI_DC';
COMMENT ON COLUMN spi_data_types.when_created IS 'When was this record created.';
COMMENT ON COLUMN spi_data_types.when_updated IS 'When was this record updated.';
COMMENT ON COLUMN spi_data_types.who_created IS 'Who created this record.';
COMMENT ON COLUMN spi_data_types.who_updated IS 'Who last updated this record.';
ALTER TABLE spi_data_types ADD UNIQUE (prompt);
ALTER TABLE spi_data_types ADD PRIMARY KEY (data_type_id);

CREATE TABLE spi_document_catalogs (
	document_catalog_id bigint ,
	document_type varchar(25) ,
	document_description varchar(512),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp,
	display_sequence smallint
) ;
COMMENT ON TABLE spi_document_catalogs IS 'Document types that may be referred to by entities within SPI.';
COMMENT ON COLUMN spi_document_catalogs.display_sequence IS 'DISPLAY SEQUENCE is used to sort the documents displayed in the application by an ordered list of document catalog types.';
COMMENT ON COLUMN spi_document_catalogs.document_catalog_id IS 'System generated identifier for this document type.';
COMMENT ON COLUMN spi_document_catalogs.document_description IS 'The description of a document type.';
COMMENT ON COLUMN spi_document_catalogs.document_type IS 'The name of a document type.';
COMMENT ON COLUMN spi_document_catalogs.when_created IS 'When was this record created.';
COMMENT ON COLUMN spi_document_catalogs.when_updated IS 'When was this record updated.';
COMMENT ON COLUMN spi_document_catalogs.who_created IS 'Who created this record.';
COMMENT ON COLUMN spi_document_catalogs.who_updated IS 'Who last updated this record.';
ALTER TABLE spi_document_catalogs ADD PRIMARY KEY (document_catalog_id);

CREATE TABLE spi_form_line_columns (
	method_type_cd varchar(50) ,
	version_no real ,
	data_type_id bigint ,
	form_line_column_id bigint ,
	display_sequence integer ,
	critical varchar(1) ,
	mandatory varchar(1) ,
	total_count_ind varchar(1),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE spi_form_line_columns IS 'The use of a Data-Type as a column on a Wildlife-Observation formfor a Species-Method-Typ';
COMMENT ON COLUMN spi_form_line_columns.critical IS 'Critical attributes which MUST be included in SPI';
COMMENT ON COLUMN spi_form_line_columns.data_type_id IS 'System generated identifier for a Data-Type.';
COMMENT ON COLUMN spi_form_line_columns.display_sequence IS 'The display sequence order for the columns on an observation form';
COMMENT ON COLUMN spi_form_line_columns.form_line_column_id IS 'System generated identifier for a Data-Type.';
COMMENT ON COLUMN spi_form_line_columns.mandatory IS 'Mandatory column defined by the RIC data-forms';
COMMENT ON COLUMN spi_form_line_columns.method_type_cd IS 'Code for a Species-Method-Typ';
COMMENT ON COLUMN spi_form_line_columns.total_count_ind IS ' Should this column in this form be included in the total count for the obs?';
COMMENT ON COLUMN spi_form_line_columns.version_no IS 'The version number of the RIC species inventory data forms';
COMMENT ON COLUMN spi_form_line_columns.when_created IS 'When was this record created.';
COMMENT ON COLUMN spi_form_line_columns.when_updated IS 'When was this record updated.';
COMMENT ON COLUMN spi_form_line_columns.who_created IS 'Who created this record.';
COMMENT ON COLUMN spi_form_line_columns.who_updated IS 'Who last updated this record.';
CREATE INDEX flc_dt_fk_i ON spi_form_line_columns (data_type_id);
CREATE UNIQUE INDEX flc_uk1_id ON spi_form_line_columns (form_line_column_id);
ALTER TABLE spi_form_line_columns ADD PRIMARY KEY (method_type_cd,version_no,data_type_id);

ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023139 CHECK ( critical IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023140 CHECK ( mandatory IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023141 CHECK ( total_count_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023143 CHECK ( critical IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023144 CHECK ( mandatory IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023145 CHECK ( total_count_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023146 CHECK ( critical IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023147 CHECK ( mandatory IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023148 CHECK ( total_count_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023149 CHECK ( critical IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023150 CHECK ( mandatory IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023151 CHECK ( total_count_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023152 CHECK ( critical IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023153 CHECK ( mandatory IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023154 CHECK ( total_count_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023155 CHECK ( critical IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023156 CHECK ( mandatory IN ( 'N' , 'Y' ));
ALTER TABLE spi_form_line_columns ADD CONSTRAINT sys_c0023157 CHECK ( total_count_ind IN ( 'N' , 'Y' ));

CREATE TABLE spi_species_method_types (
	method_type_cd varchar(50) ,
	version_no real ,
	obs_type varchar(25) ,
	form_name varchar(100) ,
	frozen_ind varchar(1) ,
	help_text varchar(512),
	end_date timestamp,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE spi_species_method_types IS 'A method of surveying wildlife species that is documented by a RICmanual and a paper form with only one type of observ';
COMMENT ON COLUMN spi_species_method_types.end_date IS 'The data when the Method Type expires.';
COMMENT ON COLUMN spi_species_method_types.form_name IS 'The form name associated with a species method.';
COMMENT ON COLUMN spi_species_method_types.frozen_ind IS 'Prevents changes to the data driven form for this method.';
COMMENT ON COLUMN spi_species_method_types.help_text IS 'Descriptive help text associated with a species method.';
COMMENT ON COLUMN spi_species_method_types.method_type_cd IS 'Code for a Species-Method-Typ';
COMMENT ON COLUMN spi_species_method_types.obs_type IS 'Obs Type is the type of data stored in this Species Method Typ';
COMMENT ON COLUMN spi_species_method_types.version_no IS 'The version number of the Species Method Type.';
COMMENT ON COLUMN spi_species_method_types.when_created IS 'When was this record created.';
COMMENT ON COLUMN spi_species_method_types.when_updated IS 'When was this record updated.';
COMMENT ON COLUMN spi_species_method_types.who_created IS 'Who created this record.';
COMMENT ON COLUMN spi_species_method_types.who_updated IS 'Who last updated this record.';
ALTER TABLE spi_species_method_types ADD PRIMARY KEY (method_type_cd,version_no);

ALTER TABLE spi_species_method_types ADD CONSTRAINT sys_c0023158 CHECK ( frozen_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_species_method_types ADD CONSTRAINT sys_c0023160 CHECK ( frozen_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_species_method_types ADD CONSTRAINT sys_c0023161 CHECK ( frozen_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_species_method_types ADD CONSTRAINT sys_c0023162 CHECK ( frozen_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_species_method_types ADD CONSTRAINT sys_c0023163 CHECK ( frozen_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_species_method_types ADD CONSTRAINT sys_c0023164 CHECK ( frozen_ind IN ( 'N' , 'Y' ));

CREATE TABLE spi_users (
	user_name varchar(20) ,
	first_name varchar(50) ,
	last_name varchar(50) ,
	melp_ind varchar(1) ,
	email_address varchar(100),
	expiry_date timestamp,
	project_create_ind varchar(1),
	note varchar(2000),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE spi_users IS 'A user of SPI_DC or SPI_OPD.  Used for granting access and roles tospecific projects';
COMMENT ON COLUMN spi_users.email_address IS 'The email address of the user';
COMMENT ON COLUMN spi_users.expiry_date IS 'The date that the user''s access should expire.';
COMMENT ON COLUMN spi_users.first_name IS 'The first name of the user';
COMMENT ON COLUMN spi_users.last_name IS 'The last name of the user';
COMMENT ON COLUMN spi_users.melp_ind IS 'Is the user a MELP employeet (Y/N)';
COMMENT ON COLUMN spi_users.note IS 'Information about the user.';
COMMENT ON COLUMN spi_users.project_create_ind IS 'Indicates whether or not a User can create a project in SPI_DC.';
COMMENT ON COLUMN spi_users.user_name IS 'The Oracle username of the SPI user';
COMMENT ON COLUMN spi_users.when_created IS 'When was this record created.';
COMMENT ON COLUMN spi_users.when_updated IS 'When was this record updated.';
COMMENT ON COLUMN spi_users.who_created IS 'Who created this record.';
COMMENT ON COLUMN spi_users.who_updated IS 'Who last updated this record.';
ALTER TABLE spi_users ADD PRIMARY KEY (user_name);
ALTER TABLE spi_users ADD UNIQUE (first_name,last_name);

ALTER TABLE spi_users ADD CONSTRAINT sys_c0023167 CHECK ( melp_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023168 CHECK ( project_create_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023169 CHECK ( melp_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023170 CHECK ( project_create_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023171 CHECK ( melp_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023172 CHECK ( project_create_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023173 CHECK ( melp_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023174 CHECK ( project_create_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023175 CHECK ( melp_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023176 CHECK ( project_create_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023177 CHECK ( melp_ind IN ( 'N' , 'Y' ));
ALTER TABLE spi_users ADD CONSTRAINT sys_c0023178 CHECK ( project_create_ind IN ( 'N' , 'Y' ));

CREATE TABLE wldstd_refs (
	id bigint ,
	standard_publication varchar(100) ,
	note varchar(2000),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldstd_refs IS 'Bibliography of text books, journals, articles, web pages, reports and other references that are used to substantiate a taxonomic record. May be used for other purposes related to other applications.';
COMMENT ON COLUMN wldstd_refs.id IS 'System generated unique identifier.';
COMMENT ON COLUMN wldstd_refs.note IS 'Standard reference notes';
COMMENT ON COLUMN wldstd_refs.standard_publication IS 'Title of the Standard Reference.';
COMMENT ON COLUMN wldstd_refs.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldstd_refs.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldstd_refs.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldstd_refs.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
ALTER TABLE wldstd_refs ADD PRIMARY KEY (id);

CREATE TABLE wldtaxonomic_units (
	id bigint ,
	unit_name1 varchar(50) ,
	unit_name2 varchar(50),
	unit_name3 varchar(50),
	taxon_authority varchar(100),
	code varchar(35),
	english_name varchar(50),
	tty_kingdom varchar(10) ,
	tty_name varchar(20) ,
	tcn_id bigint,
	txn_id bigint,
	sensitive_data_flag varchar(1),
	breed_in_bc_flag varchar(1),
	introduced_species_flag varchar(1),
	phylo_sort_sequence bigint,
	update_userid varchar(35),
	update_date timestamp,
	start_date timestamp,
	end_date timestamp,
	note varchar(2000),
	when_created timestamp ,
	when_updated timestamp,
	who_created varchar(30) ,
	who_updated varchar(30),
	element_subnational_id bigint
) ;
COMMENT ON TABLE wldtaxonomic_units IS 'A class of organisms defined according to their presumed natural relationship. The taxonomy is organized as a hierarchy from kingdom 
to subspecies.';
COMMENT ON COLUMN wldtaxonomic_units.breed_in_bc_flag IS 'Indicates whether or not an animal breeds in BC.';
COMMENT ON COLUMN wldtaxonomic_units.code IS 'Code commonly used to identify a taxon usually at a species or su';
COMMENT ON COLUMN wldtaxonomic_units.element_subnational_id IS 'Identifier that can be used to link this record to the matching Biotics field.';
COMMENT ON COLUMN wldtaxonomic_units.end_date IS 'The date a taxon becomes obsolete.';
COMMENT ON COLUMN wldtaxonomic_units.english_name IS 'Common english name of the species or taxa. Ex. Grizzly Bear';
COMMENT ON COLUMN wldtaxonomic_units.id IS 'System generated UID for a taxon.';
COMMENT ON COLUMN wldtaxonomic_units.introduced_species_flag IS 'Indicates that species is not native to British Columbia.';
COMMENT ON COLUMN wldtaxonomic_units.note IS 'Free form text about the taxon.';
COMMENT ON COLUMN wldtaxonomic_units.phylo_sort_sequence IS 'The phologenetic sequence order of the taxon.';
COMMENT ON COLUMN wldtaxonomic_units.sensitive_data_flag IS 'Indicates that the data is sensitive and access restricted';
COMMENT ON COLUMN wldtaxonomic_units.start_date IS 'The date the taxon name becomes effective.';
COMMENT ON COLUMN wldtaxonomic_units.taxon_authority IS 'Name of the author(s) who first described the species, eg. Linna';
COMMENT ON COLUMN wldtaxonomic_units.tcn_id IS 'FK: WLD_COMMON_NAMES';
COMMENT ON COLUMN wldtaxonomic_units.tty_kingdom IS 'The kingdom the taxon hierarchy represents';
COMMENT ON COLUMN wldtaxonomic_units.tty_name IS 'The name of the taxon level, eg. PHYLUM, ORDER, GENUS, etc';
COMMENT ON COLUMN wldtaxonomic_units.txn_id IS 'System generated UID for a taxon.';
COMMENT ON COLUMN wldtaxonomic_units.unit_name1 IS 'The first part of a species or taxon  name.';
COMMENT ON COLUMN wldtaxonomic_units.unit_name2 IS 'Idenifies the species.';
COMMENT ON COLUMN wldtaxonomic_units.unit_name3 IS 'Subspecies name.';
COMMENT ON COLUMN wldtaxonomic_units.update_date IS 'The last date that the record was changed.';
COMMENT ON COLUMN wldtaxonomic_units.update_userid IS 'The last user to change the record.';
COMMENT ON COLUMN wldtaxonomic_units.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxonomic_units.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxonomic_units.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxonomic_units.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_txn_tcn_id ON wldtaxonomic_units (tcn_id);
CREATE INDEX wld_txn_tty_kingdom_name ON wldtaxonomic_units (tty_kingdom, tty_name);
CREATE INDEX wld_txn_txn_id ON wldtaxonomic_units (txn_id);
CREATE INDEX wld_txn_unit_name1_2 ON wldtaxonomic_units (unit_name1, unit_name2);
ALTER TABLE wldtaxonomic_units ADD PRIMARY KEY (id);

CREATE TABLE wldtaxon_adhoc_grps (
	id bigint ,
	name varchar(50) ,
	correlator varchar(50),
	description varchar(2000),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_adhoc_grps IS 'A classification, other than a taxonomic rank, that can be used to group taxonomic units, such as ''ungulat'' in the animal kingdom, or ''woody shrub'' in the plant kingdom.';
COMMENT ON COLUMN wldtaxon_adhoc_grps.correlator IS 'The person responsible for defining the adhoc group';
COMMENT ON COLUMN wldtaxon_adhoc_grps.description IS 'Free form text about the ad-hoc group';
COMMENT ON COLUMN wldtaxon_adhoc_grps.id IS 'A number that uniquely identifies the ad hoc group';
COMMENT ON COLUMN wldtaxon_adhoc_grps.name IS 'Descriptive name fully qualifying the adhoc group';
COMMENT ON COLUMN wldtaxon_adhoc_grps.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_adhoc_grps.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_adhoc_grps.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_adhoc_grps.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
ALTER TABLE wldtaxon_adhoc_grps ADD UNIQUE (name);
ALTER TABLE wldtaxon_adhoc_grps ADD PRIMARY KEY (id);

CREATE TABLE wldtaxon_adhoc_grp_mbrs (
	tgp_id bigint ,
	txn_id bigint ,
	start_date timestamp ,
	end_date timestamp,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_adhoc_grp_mbrs IS 'A particular taxonomic unit associated with a particular taxon adhoc group. For example, salmon berry may be a member of the ''woody shrub'' taxon adhoc group.';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.end_date IS 'The date a membership is terminated';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.start_date IS 'The date that a taxon becomes part of an adhoc group.';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.tgp_id IS 'FK: TaxonAdhocGroups A number that uniquely identifies the ad hoc group';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.txn_id IS 'FK: TaxonomicUnit The taxon that is a member of the adhoc group.';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_adhoc_grp_mbrs.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_tam_tgp_id ON wldtaxon_adhoc_grp_mbrs (tgp_id);
CREATE INDEX wld_tam_txn_id ON wldtaxon_adhoc_grp_mbrs (txn_id);
ALTER TABLE wldtaxon_adhoc_grp_mbrs ADD PRIMARY KEY (tgp_id,txn_id);

CREATE TABLE wldtaxon_refs (
	srf_id bigint ,
	txn_id bigint ,
	current_standard varchar(1) ,
	description varchar(2000),
	start_date timestamp ,
	end_date timestamp,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_refs IS 'A particular standard-reference used as a source of information for a particular taxonomic-unit.  Although many taxon-references may be recorded for a particular taxonomic-unit, only one of these is identified as the ''current standard'' at any given point in time.';
COMMENT ON COLUMN wldtaxon_refs.current_standard IS 'Y/N : Indicates whether the document is the current standard';
COMMENT ON COLUMN wldtaxon_refs.description IS 'Free-form text about the taxon reference.';
COMMENT ON COLUMN wldtaxon_refs.end_date IS 'The date the reference is no longer current.';
COMMENT ON COLUMN wldtaxon_refs.srf_id IS 'FK: StandardReference A reference for a taxon.';
COMMENT ON COLUMN wldtaxon_refs.start_date IS 'The effective date of the taxon referenc';
COMMENT ON COLUMN wldtaxon_refs.txn_id IS 'FK: TaxonomicUnit The taxon that a reference is recorded for.';
COMMENT ON COLUMN wldtaxon_refs.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_refs.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_refs.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_refs.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_trf_srf_id ON wldtaxon_refs (srf_id);
CREATE INDEX wld_trf_txn_id ON wldtaxon_refs (txn_id);
ALTER TABLE wldtaxon_refs ADD PRIMARY KEY (srf_id,txn_id);

CREATE TABLE wldtaxon_statuses (
	tst_status_type_cd varchar(20) ,
	status_cd varchar(20) ,
	note varchar(2000),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_statuses IS 'The status of a taxon.';
COMMENT ON COLUMN wldtaxon_statuses.note IS 'Text about StatusCod';
COMMENT ON COLUMN wldtaxon_statuses.status_cd IS 'Code for a  wildlife status. Ex:RED, BLUE, YELLOW, EXTINCT';
COMMENT ON COLUMN wldtaxon_statuses.tst_status_type_cd IS 'FK: StatusTypes Code identifying type ofstatus';
COMMENT ON COLUMN wldtaxon_statuses.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_statuses.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_statuses.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_statuses.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_txs_tst_type_cd ON wldtaxon_statuses (tst_status_type_cd);
ALTER TABLE wldtaxon_statuses ADD PRIMARY KEY (tst_status_type_cd,status_cd);

CREATE TABLE wldtaxon_status_types (
	status_type_cd varchar(20) ,
	name varchar(50) ,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_status_types IS 'The type of Taxon status as defined by the monitoring body.';
COMMENT ON COLUMN wldtaxon_status_types.name IS 'Full name of the StatusType.';
COMMENT ON COLUMN wldtaxon_status_types.status_type_cd IS 'Code identifying a type of wildlife status.';
COMMENT ON COLUMN wldtaxon_status_types.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_status_types.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_status_types.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_status_types.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
ALTER TABLE wldtaxon_status_types ADD PRIMARY KEY (status_type_cd);

CREATE TABLE wldtaxon_syns (
	txn_id bigint ,
	txn_id_an_old_name_for bigint ,
	start_date timestamp ,
	end_date timestamp,
	reason varchar(20),
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_syns IS 'A relationship between an accepted taxonomic name and a predecessor to it. Used to record the former record(s) used to identify a taxon. Allows queries on observations of a taxon to include observations made on a former name for that taxon.';
COMMENT ON COLUMN wldtaxon_syns.end_date IS 'Date on which the synonym ceases to be valid';
COMMENT ON COLUMN wldtaxon_syns.reason IS 'Reason for creating the synonym, eg. "split"';
COMMENT ON COLUMN wldtaxon_syns.start_date IS 'The date a new name was identified or recorded.';
COMMENT ON COLUMN wldtaxon_syns.txn_id IS 'FK: TaxonmicUnit The Taxon that has a synonym.';
COMMENT ON COLUMN wldtaxon_syns.txn_id_an_old_name_for IS 'FK: TaxonomicUnit. The taxon that is a synonym.';
COMMENT ON COLUMN wldtaxon_syns.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_syns.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_syns.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_syns.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_tsn_txn_id ON wldtaxon_syns (txn_id);
CREATE INDEX wld_tsn_txn_id_old_name ON wldtaxon_syns (txn_id_an_old_name_for);
ALTER TABLE wldtaxon_syns ADD PRIMARY KEY (txn_id,txn_id_an_old_name_for);

CREATE TABLE wldtaxon_types (
	kingdom varchar(10) ,
	name varchar(20) ,
	hierarchy_level smallint ,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_types IS 'Levels in the taxonomic classification hierarchy for each Kingdom. Ex. Phylum, Class, Order, Family, Genus, Species, Subspecies.';
COMMENT ON COLUMN wldtaxon_types.hierarchy_level IS 'A number indicating the sequence of this taxon type in the hierar';
COMMENT ON COLUMN wldtaxon_types.kingdom IS 'The kingdom the taxon hierarchy represents';
COMMENT ON COLUMN wldtaxon_types.name IS 'The name of the taxon level, eg. PHYLUM, ORDER, GENUS, etc';
COMMENT ON COLUMN wldtaxon_types.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_types.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_types.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_types.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
ALTER TABLE wldtaxon_types ADD PRIMARY KEY (kingdom,name);

CREATE TABLE wldtaxon_unit_status (
	tst_status_type_cd varchar(20) ,
	txn_id bigint ,
	start_date timestamp ,
	end_date timestamp,
	qualifier_code varchar(10),
	txs_status_cd varchar(20) ,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wldtaxon_unit_status IS 'The status of taxonomic unit for a taxon status type for a period of time.';
COMMENT ON COLUMN wldtaxon_unit_status.end_date IS 'The date that a classification of an organism became invalid.';
COMMENT ON COLUMN wldtaxon_unit_status.qualifier_code IS 'A code that qualifies a TaxonStatus.';
COMMENT ON COLUMN wldtaxon_unit_status.start_date IS 'The date that a classification became valid or was recorded';
COMMENT ON COLUMN wldtaxon_unit_status.tst_status_type_cd IS 'FK: StatusTypes Code for a StatusTyp';
COMMENT ON COLUMN wldtaxon_unit_status.txn_id IS 'FK: TaxonomicUnit';
COMMENT ON COLUMN wldtaxon_unit_status.txs_status_cd IS 'FK: TaxonStatus Code for the status of the taxon';
COMMENT ON COLUMN wldtaxon_unit_status.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_unit_status.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_unit_status.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wldtaxon_unit_status.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_txnunst_status_cd ON wldtaxon_unit_status (txs_status_cd);
CREATE INDEX wld_txnunst_txn_id ON wldtaxon_unit_status (txn_id);
ALTER TABLE wldtaxon_unit_status ADD PRIMARY KEY (tst_status_type_cd,txn_id,txs_status_cd);

CREATE TABLE wld_common_names (
	id bigint ,
	name varchar(50) ,
	name_level numeric(38) ,
	parent_id bigint,
	who_created varchar(30) ,
	when_created timestamp ,
	who_updated varchar(30),
	when_updated timestamp
) ;
COMMENT ON TABLE wld_common_names IS 'A hierarchical index of common names. Ex: Birds is the parent of Loons, Phalaropes and Thrushes.';
COMMENT ON COLUMN wld_common_names.id IS 'PK System generated unique identifier.';
COMMENT ON COLUMN wld_common_names.name IS 'The name of the common name index.';
COMMENT ON COLUMN wld_common_names.name_level IS 'The level of the name in the common name index hierarchy.';
COMMENT ON COLUMN wld_common_names.parent_id IS 'FK: CommonName The parent in the common name hierarchy.';
COMMENT ON COLUMN wld_common_names.when_created IS 'When was this record created. Used by Warehouse processes.';
COMMENT ON COLUMN wld_common_names.when_updated IS 'When was this record last updated.Used by Warehouse processes.';
COMMENT ON COLUMN wld_common_names.who_created IS 'Who created this record. Used by Warehouse processes.';
COMMENT ON COLUMN wld_common_names.who_updated IS 'Who last updated this record.Used by Warehouse processes.';
CREATE INDEX wld_tcn_parent_id ON wld_common_names (parent_id);
ALTER TABLE wld_common_names ADD PRIMARY KEY (id);
ALTER TABLE wld_common_names ADD UNIQUE (name);

ALTER TABLE spi_form_line_columns ADD CONSTRAINT flc_dt_fk FOREIGN KEY (data_type_id) REFERENCES spi_data_types(data_type_id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE spi_form_line_columns ADD CONSTRAINT flc_smt_fk FOREIGN KEY (method_type_cd,version_no) REFERENCES spi_species_method_types(method_type_cd,version_no) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wldtaxonomic_units ADD CONSTRAINT txn_tcn_fk FOREIGN KEY (tcn_id) REFERENCES wld_common_names(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE wldtaxonomic_units ADD CONSTRAINT txn_tty_fk FOREIGN KEY (tty_kingdom,tty_name) REFERENCES wldtaxon_types(kingdom,name) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE wldtaxonomic_units ADD CONSTRAINT txn_txn_fk FOREIGN KEY (txn_id) REFERENCES wldtaxonomic_units(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wldtaxon_adhoc_grp_mbrs ADD CONSTRAINT tam_txngrp_fk FOREIGN KEY (tgp_id) REFERENCES wldtaxon_adhoc_grps(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE wldtaxon_adhoc_grp_mbrs ADD CONSTRAINT tam_txn_fk FOREIGN KEY (txn_id) REFERENCES wldtaxonomic_units(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wldtaxon_refs ADD CONSTRAINT trf_srf_fk FOREIGN KEY (srf_id) REFERENCES wldstd_refs(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE wldtaxon_refs ADD CONSTRAINT trf_txn_fk FOREIGN KEY (txn_id) REFERENCES wldtaxonomic_units(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wldtaxon_statuses ADD CONSTRAINT txs_tst_fk FOREIGN KEY (tst_status_type_cd) REFERENCES wldtaxon_status_types(status_type_cd) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wldtaxon_syns ADD CONSTRAINT tsn_txn_id_fk FOREIGN KEY (txn_id) REFERENCES wldtaxonomic_units(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE wldtaxon_syns ADD CONSTRAINT tsn_txn_old_name_fk FOREIGN KEY (txn_id_an_old_name_for) REFERENCES wldtaxonomic_units(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wldtaxon_unit_status ADD CONSTRAINT txnunst_txn_fk FOREIGN KEY (txn_id) REFERENCES wldtaxonomic_units(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE wldtaxon_unit_status ADD CONSTRAINT txnunst_txs_fk FOREIGN KEY (tst_status_type_cd,txs_status_cd) REFERENCES wldtaxon_statuses(tst_status_type_cd,status_cd) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE wld_common_names ADD CONSTRAINT tcn_tcn_fk FOREIGN KEY (parent_id) REFERENCES wld_common_names(id) ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE;
